const userTypes = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  FACEBOOK_SIGN_IN_START: "FACEBOOK_SIGN_IN_START"
};

export default userTypes;
