const userTypes = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  FACEBOOK_SIGN_IN_START: "FACEBOOK_SIGN_IN_START",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  REGISTER_EMAIL_START: "REGISTER_EMAIL_START",
  REGISTER_EMAIL_SUCCESS: "REGISTER_EMAIL_SUCCESS",
  REGISTER_EMAIL_FAILURE: "REGISTER_EMAIL_FAILURE",
  SIGN_IN_WITH_EMAIL: "SIGN_IN_WITH_EMAIL"
};

export default userTypes;
